import { DocType, FormStatus } from ".";

export type ApplicationFormDocType = DocType;
export type PGFormDocType = DocType;
export type WorkExDocType = DocType;
export type ExtraCurDocType = DocType;
export type InternDocType = DocType;
export type CompetitiveFormDocType = DocType;

export interface ApplicationFormView {
  name: string;
  docstatus: FormStatus;
  modified: string;
  enable_scholarship_form: number;
}

// {
//       name: 'ADM-2026-00009',
//       owner: 'Administrator',
//       creation: '2026-06-12 01:12:24.932488',
//       modified_by: 'Administrator',
//       docstatus: 0,
//       idx: 0,
//       choose_the_one_that_describes_you: '',
//       crm_lead: null,
//       how_do_you_plan_to_finance_your_education: '',
//       enable_scholarship_form: 0,
//       program: '',
//       title: '',
//       first_name: null,
//       middle_name: null,
//       last_name: null,
//       email_id: 'dev@makeamine.com',
//       mobile_number: null,
//       date_of_birth: '2003-12-02',
//       age_as_on_30th_june_2026: 0,
//       category: '',
//       if_other_please_enter_here: null,
//       physically_challenged: '',
//       if_yes_please_specify: null,
//       where_did_you_hear_about_vedica_: '',
//       have_you_applied_to_vedica_before: '',
//       which_year: null,
//       which_of_these_vedica_offerings_is_the_most_important_to_you: '',
//       fathers_title: '',
//       fathers_full_name: null,
//       fathers_mobile_number: null,
//       fathers_email: null,
//       fathers_organisation: '',
//       father_sector: '',
//       fathers_designation: null,
//       father_organisation__reason: null,
//       mothers_title: '',
//       mothers_full_name: null,
//       mothers_mobile_number: null,
//       mothers_email: null,
//       mothers_organisation: '',
//       mothers_organisation__reason: null,
//       mother_sectors: '',
//       mothers_designation: null,
//       annual_family_income_family_yours_if_working: '',
//       guardians_title: '',
//       guardian_full_name: null,
//       guardians_mobile_number: null,
//       guardians_email: null,
//       guardians_organisation: '',
//       guardians_organisation_other_resaon: null,
//       guardians_designation: null,
//       guardians_academic_qualification: null,
//       country: 'India',
//       state: '',
//       district: null,
//       address_line_1: null,
//       address_line_2: null,
//       pincode: 0,
//       is_permanent_address_same_as_current_address: '',
//       country_permanent_address: null,
//       address_line1: null,
//       address_line2: null,
//       pincode_permanent_address: 0,
//       name_of_institution: null,
//       board: '',
//       if_other_please_enter_resaon: null,
//       year_of_passing: null,
//       marking_scheme: '',
//       maximum_marks: 0,
//       marks_obtained: 0,
//       obtained_percentagecgpa: 0,
//       medium_of_education: '',
//       name_of_institutions: null,
//       boards: '',
//       if_other_please_enter_reason: null,
//       stream: null,
//       year_of_passings: null,
//       marking_schemes: '',
//       maximum_markss: 0,
//       marks_obtaineds: 0,
//       obtained_percentagecgpas: 0,
//       medium_of_educations: '',
//       name_of_institutions_undergraduate: null,
//       university: '',
//       if_other_please_specify: null,
//       streams_under_gradaute: 'BFA',
//       if_other_please_specify_for_stream: null,
//       course_name: null,
//       city: null,
//       marks_obtaineds_undergraduate: 0,
//       year_of_passing_undergraduate: null,
//       marking_scheme_undergraduate: '',
//       maximum_marks_under_graduate: 0,
//       obtained_percentagecgpas_undergrduate: 0,
//       degree_completed: '',
//       have_you_taken_any_competitive_exams_before: '',
//       do_you_have_any_work_experience: '',
//       do_you_have_internship_experience: '',
//       do_you_have_any_work_references: '',
//       full_name: null,
//       email: null,
//       work_experience_mobilenumber: null,
//       organization_name: null,
//       designation: null,
//       website: null,
//       social_media_links: null,
//       women_independence: '',
//       challenge_overcome: null,
//       career_aspirations: null,
//       explain_dedica: null,
//       facebook: null,
//       instagram: null,
//       linkedin: null,
//       twitter: null,
//       blog: null,
//       any_thing_else: null,
//       upload_your_recent_passport_size_photograph: null,
//       '10th_marksheet': null,
//       under_graduation_details: null,
//       upload_your_resume: null,
//       '12th_marksheet': null,
//       post_graduate_marksheet: null,
//       applicant_name: null,
//       parent_name: null,
//       date: null,
//       amended_from: null
//     }
